### ISSUE TITLE
Large economy operations freeze server

### ISSUE THREAD

**Issue by Kwikxilver** [TheNewEconomy/TNE-Bukkit#430] opened 2020-07-20 21:22 UTC
#### What is the issue/bug you're experiencing?

Using TNE-1.1.9.3.jar with DynamicShop 2.11.8.jar. I'm using MySQL as my database for TNE. Running Paper-101.

For some reason whenever I make a x64 item purchase in DynamicShop (and sometimes a x32 item purchase) the server grinds to a halt and Paper spits out an error in the console after resolving the purchase. This happens whenever a player makes a purchase. 

Left unchecked, the server eventually bricks itself (no console logs, players do not register as logged out).

[I reported this on DynamicShop's github](https://github.com/7sat/SSDynamicShop/issues/33#issuecomment-657296244) and was advised to take it up with you at TNE as it's an issue with getting player balances.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)

1. Install TNE and [DynamicShop](https://www.spigotmc.org/resources/ss-dynamic-shop-1-13-1-16.65603/)
2. Make a large purchase (x64 items) from a DynamicShop.
3. Server freezes for a second, spits out an error in console.
4. (later) server eventually stops responding or printing messages in console. Players unable to log out or log in.

#### TNE version?(exact version number), and whether or not you've made modification to it.

TNE-1.1.9.3.jar, no mods.

#### TNE build?(/tne build), and whether or not you've made modification to it.

TNE build 0.1.1.9d. No modifications, I am using the version from your github.

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.

I don't think I've loaded any modules. I'm just using whatever it loads as stock.

#### Spigot/Bukkit version?

Using Paper-101 for MC 1.16.1.

#### Is your server run in online mode?

Yes.

#### The exact command you ran w/ arguments?

No command, I was simply making a large purchase through DynamicShop.

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)

[Here's my config.yml.](https://paste.ubuntu.com/p/dNwbYtv3bT/)

#### Your latest server log file?(use http://paste.ubuntu.com)

[Error (stopped right after slowdown)](https://paste.ubuntu.com/p/7ngwNVDnvk/)

[Full server log.](https://paste.ubuntu.com/p/5zxzpHtgpS/)

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

n/a

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment] 2020-07-20 22:27
The issue is in part fact due to paper/spigot running a check against the Mojang api on the main thread. I'm currently looking at ways to go around this.

**Comment by creatorfromhell** [comment] 2020-08-29 21:51
Seems to be fixed in latest builds from what I've tested.

**Closed by creatorfromhell** 2020-08-29 21:51 UTC
Labels: Type: Bug
