### ISSUE TITLE
Slow offline economy processing

### ISSUE THREAD

**Issue by JohnS19** [TheNewEconomy/TNE-Bukkit#362] opened 2019-11-22 23:53 UTC
What is the issue/bug you're experiencing?
Slow offline processing of economy in chestshop plugin.
 
How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Download Quickshop Remake and try purchasing an item from an offline user.
 
TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9
 
TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119
 
Modules Loaded?(exact version number), and whether or not you've made modification to it.
0
 
Spigot/Bukkit version?
Paper 226
 
Is your server run in online mode?
No
 
The exact command you ran w/ arguments?
N/A
 
config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/nch5PQH9dd/
 
Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/cZcPrGgfx7/

**Comment by creatorfromhell** [comment] 2019-11-23 15:49
Seems to be the same amount of time for online and offline. https://www.youtube.com/watch?v=s8YGV-NA5_g

**Comment by JohnS19** [comment] 2019-11-23 20:15
I seem to be getting this every time I attempt it:

[QuickShop] Failed to deposit the money for player CraftOfflinePlayer[UUID=33be0127-2d37-401e-91d2-c1664880a398]

**Comment by creatorfromhell** [comment] 2019-11-23 20:40
> I seem to be getting this every time I attempt it:
> https://paste.ubuntu.com/p/gvb2Mf2RVk/
> 
> Looks like it isn't recognizing the offline players economy account for some reason? Maybe this has something to do with the mysql db system?

I've tested on both h2 and mysql, unable to recreate. Please update with a recreation method that is able to accurately recreate this issue.

**Comment by JohnS19** [comment] 2019-11-24 03:14
Oh sorry,  it should start occurring if you set your test server in **offline mode**.

**Comment by creatorfromhell** [comment] 2019-11-24 03:51
> Oh sorry, it should start occurring once you set your test server to **offline mode**.

I've put my server in offline mode now and it still works as intended.

**Comment by JohnS19** [comment] 2019-11-24 07:51
I'm not exactly sure what it is, but it is the same as doing /tne delete on the shop owner. I'm not sure why the account is being deleted as of yet... While players that are online have normally functioning shops.

**Comment by JohnS19** [comment] 2019-11-24 18:52
Could this be because of running off of bungee?

**Comment by JohnS19** [comment] 2019-11-24 20:12
Here is a spark profile of when it happens. https://sparkprofiler.github.io/#ePMfpQH8rt

**Comment by creatorfromhell** [comment] 2019-11-24 21:15
> Here is a spark profile of when it happens. https://sparkprofiler.github.io/#ePMfpQH8rt
> 
> Is there anyway to make a cache to give them offline balances when they login rather than what it's doing right now?

None of this is providing a form of recreation. As stated above give a step by step peocedure done to recreate the issue. Currently the ones provided dont provide the same results

**Comment by JohnS19** [comment] 2019-11-25 17:21
I'm not able to give a step-by-step procedure on how to repeat this scenario but it's clearly there:
![image](https://user-images.githubusercontent.com/48459351/69562858-e583fc80-0f64-11ea-9ade-d16b587c8b64.png)

**Comment by JohnS19** [comment] 2019-11-27 22:17
Can you add a feature where it would cache the balance changes for offline players and wait till they are online?

**Comment by creatorfromhell** [comment] 2019-11-28 05:18
> Can you add a feature where it would cache the balance changes for offline players and wait till they are online?

Caching was removed from tne for a reason and will not return.

**Comment by JohnS19** [comment] 2019-11-28 17:23
Okay, now towny is causing crashes because of TNE's offline processing when upkeep time comes around.

**Comment by creatorfromhell** [comment] 2019-11-29 00:35
Im closing this until a reproduction method is provided as i already asked for this but we keep adding comments without the reproduction method.

**Closed by creatorfromhell** 2019-11-29 00:35 UTC
Labels: Type: Can't Reproduce

**Comment by Floffah** [comment] 2020-07-24 17:47
i am having this same issue

**Comment by creatorfromhell** [comment] 2020-07-24 22:43
> i am having this same issue

As stated multiple times on the discord. This is due to internal spigot/bukkit methods. Currently seeking work around but until then this is as optimized as it can get.
