### ISSUE TITLE
Server_name field is not using the server name on the config

### ISSUE THREAD

**Issue by xion87** [TheNewEconomy/TNE-Bukkit#379] opened 2020-01-28 12:25 UTC
#### What is the issue/bug you're experiencing?
New players in TNE_BALANCES the column "server_name"  are alway saved as "Main Server" instead the server name specified on config

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Using mysql, setting a server name on TNE config and allowing new user to enter and use economy

#### TNE version?(exact version number), and whether or not you've made modification to it.
 0.1.1.9b

#### TNE build?(/tne build), and whether or not you've made modification to it.
You're currently running TNE build 1Beta119b

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules loaded

#### Spigot/Bukkit version?
Paper(77) 1.15.2-R0.1-SNAPSHOT

#### Is your server run in online mode?
Nope

#### The exact command you ran w/ arguments?
/

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://gist.github.com/xion87/aaf4347c427e3448b23a079a0ef6f79d

#### Your latest server log file?(use http://paste.ubuntu.com)
Not relevant

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
Not relevant

**Comment by creatorfromhell** [comment] 2020-01-28 13:40
Cant reproduce this.

**Comment by xion87** [comment] 2020-01-28 13:41
try to use my exact server name

**Comment by creatorfromhell** [comment] 2020-01-28 14:48
Marking this as closed, it appears to be a case where I found this since last release and fixed it locally.

**Closed by creatorfromhell** 2020-01-28 14:48 UTC
Labels: Type: Bug, Type: Can't Reproduce
