### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Snowent** [TheNewEconomy/TNE-Bukkit#513] opened 2022-09-17 01:14 UTC
### TNE Version

0.1.1.17-PRE-2

### Spigot Version

1.19.2

### Your config.yml

https://pastebin.com/d435XnVD

### Your latest server log

https://pastebin.com/enCSAM6q

### What part of TNE is the bug affecting?

Transactions

### Is your server using online mode?

No

### Bug description

Player balances will stop accepting payments temporarily from Essentials /sell with no direct cause. 

### How to reproduce

Occasionally, using Essentials /sell will fail to update player balances for a random duration. Jobs Reborn automatic payments will work and using "/money give"will update the balance, but any further Essentials /sell actions won't reflect in the balance during these times. 

I know this counts as a "cracked" server as it is offline for Floodgate and Geyser to allow console connections, but this happens without any bedrock integration. I have taken an excerpt from a past log with debug while a balance was frozen, as it happens sporadically and will occasionally self-correct with no user input. On occasion, balances will fail to update with Essentials /sell right after a restart, so far I have not found a solid cause.

Frozen Balance Excerpt: https://pastebin.com/1YRMYzKv

**Comment by creatorfromhell** [comment] 2022-09-17 01:27
Do you have the message that it shows when it stops working?

**Comment by Snowent** [comment] 2022-09-17 01:40
It doesn't show a message, it gives no error or indication. people just use /sell, Essentials reports the value, and the balance fails to update.

**Comment by creatorfromhell** [comment] 2022-09-17 01:41
> It doesn't show a message, it gives no error or indication. people just use /sell, Essentials reports the value, and the balance fails to update.

Approximately how many times? I need some form of reproduction method to test this.

**Comment by Snowent** [comment] 2022-09-17 01:43
indefinitely, at line 234 in my frozen excerpt my balance is frozen - when I sell hand those calls are made, but the balance never updates. people on the server have taken to selling 1 item to see if their balance updates before selling the rest.

**Comment by Snowent** [comment] 2022-09-17 01:43
I haven't found a cause for the balance freezing, nor the balance un-freezing and updating properly. I was hoping the debug would give some clues but I am not familiar enough to read it.

**Comment by creatorfromhell** [comment] 2022-09-17 01:44
> I haven't found a cause for the balance freezing, nor the balance un-freezing and updating properly. I was hoping the debug would give some clues but I am not familiar enough to read it.

It did not provide anything... I'll test but leave this open until a reproduction cause it found or the recode is released, whichever comes first.

**Comment by Snowent** [comment] 2022-09-17 01:45
Understood - I will continue collecting what information I can.

**Comment by Snowent** [comment] 2022-09-17 02:11
https://pastebin.com/q7L0Y2c6
New Log
Line 522 begins the Debug, the player below is frozen at this time, and for an unknown time before, perhaps since the server opened with no error or indication.

Username: Kamai64
Id: 87b3b463-91f4-45f2-92ad-27f6c11c0a57

**Comment by Snowent** [comment] 2022-09-17 02:11
I have to go to work, so no rush - I'll check back in later to see if this was helpful at all.

**Comment by Snowent** [comment] 2022-09-17 10:50
Interesting Log here, Added notes with ###(note)###

https://pastebin.com/FrHTeXC6

**Comment by Snowent** [comment] 2022-09-17 11:57
At this point, I have had my balance freeze after Jobs Reborn payments on occasion(not 100%), and have been able to unfreeze the balance for /sell or other sources by getting another payment through Jobs Reborn. So far every time it's frozen, getting 1 payment corrects it, the balance update with no /sell I saw in the Log above was actually from a Jobs Reborn payment.

**Comment by creatorfromhell** [comment] 2022-09-17 15:13
Hmmm, and just to be sure, it's not going into the essentials balance correct?

**Comment by Snowent** [comment] 2022-09-17 15:59
The only place I know where to see that is in the user data. I can poke it tomorrow until my balance freezes again, and see. At this point its like, Jobs Reborn is waiting for a payment and preventing balances from changing until it receives one? like a fractional value that needs to be paid that is below the minimum, so that payment hangs until Jobs Reborn has enough value to pay it fully? I am probably using the wrong terminology to describe the process, but that is my nearest guess.

For example, I have essentials user data with a money value that looks like this: "money: '8805.486899999999'" - again, I am not familiar enough to say why, just that I have found receiving a payment from any Jobs Reborn source appears to allow Essentials /sell to reflect properly in the balance again.

**Comment by creatorfromhell** [comment] 2022-09-17 16:03
> The only place I know where to see that is in the user data. I can poke it tomorrow until my balance freezes again, and see. At this point its like, Jobs Reborn is waiting for a payment and preventing balances from changing until it receives one? like a fractional value that needs to be paid that is below the minimum, so that payment hangs until Jobs Reborn has enough value to pay it fully? I am probably using the wrong terminology to describe the process, but that is my nearest guess.
> 
> For example, I have essentials user data with a money value that looks like this: "money: '8805.486899999999'" - again, I am not familiar enough to say why, just that I have found receiving a payment from any Jobs Reborn source appears to allow Essentials /sell to reflect properly in the balance again.

Interesting, does everything hang without jobs? I'm wondering if it's something within jobs itself.

**Comment by Snowent** [comment] 2022-09-17 16:05
I am thinking its a conflict with Jobs - since I worked it out to be how things are freezing (Essentials /sell will work fine until a Jobs payment causes the Balance to freeze.)

**Comment by Snowent** [comment] 2022-09-17 16:08
This is from the Jobs Reborn Config, TNE should be fine with this right?

# Changes how often, in seconds, players are paid out. Default is 5 seconds.
# Setting this too low may cause tick lag. Increase this to improve economy performance (at the cost of delays in payment)
economy-batch-delay: 5
# Enable async economy calls.
# Disable this if you have issues with payments or your plugin is not thread safe.
economy-async: true

**Comment by creatorfromhell** [comment] 2022-09-17 16:13
Iim honestly not sure as I've never really dealt with it, but sending payments everything 5 seconds seems like a lot of payments to send

**Comment by Snowent** [comment] 2022-09-17 16:16
Its only when Job actions are done, so, someone is mining, with the miner job, it will add up 5 seconds of block breaks, then pay them all out in one batch. I also found a minimal value setting, and have disabled it just in the off chance that it is somehow that causing it?

**Comment by Snowent** [comment] 2022-09-17 16:36
Upon loading into the server, my balance was frozen, and causing Jobs payments did not unfreeze it, so I reverted the Jobs config to the default setting. At least I have a workaround for it in the interim.

**Comment by creatorfromhell** [comment] 2023-07-25 01:52
Seems to be fixed with the recode.

**Closed by creatorfromhell** 2023-07-25 01:52 UTC
