### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by elwolf6** [TheNewEconomy/TNE-Bukkit#453] opened 2021-01-12 21:55 UTC
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)

I don't know it just happened.

#### TNE version?(exact version number), and whether or not you've made modification to it.

TNE-0.1.1.13-shaded.jar You gave it to me in the discord not the pinned one though.

#### TNE build?(/tne build), and whether or not you've made modification to it.

TNE build 0.1.1.1.3-PRE-1

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.

None

#### Spigot/Bukkit version?

Tuinity (Paper fork) 1.16.4

#### Is your server run in online mode?

Bungee online mode

#### The exact command you ran w/ arguments?

None

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)

https://paste.ubuntu.com/p/hPck3KzNRG/

#### Your latest server log file?(use http://paste.ubuntu.com)

https://paste.ubuntu.com/p/57rNXFFtcp/

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by ThatOneTree** [comment] 2021-01-28 14:05
+1 Happened to me as well, randomly.

**Comment by creatorfromhell** [comment] 2021-01-28 15:53
This is caused by mojang api rate limits when finding UUIDs, hoping the cache will fix this.

**Comment by ThatOneTree** [comment] 2021-01-30 11:29
> do you have an eta for when caching will be reimplemented

I am also interested in knowing

**Comment by creatorfromhell** [comment] 2021-01-30 17:09
It all depends on the amount of work required to reimplement it into the new framework. There could be a patch within the week or it may be a couple of weeks.

**Comment by ThatOneTree** [comment] 2021-02-08 06:18
Will the new system fix the towny login lag after reboots? I am literally crashing from players joining after reboot at this point and this has been an issue for awhile now.

**Comment by creatorfromhell** [comment] 2021-07-24 13:32
Should be fixed with the cache pr.

**Closed by creatorfromhell** 2021-07-24 13:32 UTC
Labels: Type: Bug
